# Generated by Django 5.2.6 on 2025-10-08 13:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=200, verbose_name="Имя сотрудника"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=200, verbose_name="Фамилия сотрудника"),
                ),
                (
                    "photo_employee",
                    models.ImageField(
                        upload_to="photos/", verbose_name="Фото сотрудника"
                    ),
                ),
                (
                    "job_title",
                    models.CharField(max_length=200, verbose_name="Должность"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Комментарии о сотруднике"
                    ),
                ),
            ],
            options={
                "verbose_name": "сотрудник",
                "verbose_name_plural": "сотрудники",
            },
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название ресторана"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="photos/",
                        verbose_name="Логотип ресторана",
                    ),
                ),
                (
                    "story",
                    models.TextField(
                        blank=True, null=True, verbose_name="История ресторана"
                    ),
                ),
                (
                    "mission",
                    models.TextField(blank=True, null=True, verbose_name="Миссия"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание ресторана"
                    ),
                ),
            ],
            options={
                "verbose_name": "ресторан",
                "verbose_name_plural": "рестораны",
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "table_number",
                    models.PositiveIntegerField(
                        help_text="Укажите номер стола",
                        unique=True,
                        verbose_name="Номер стола",
                    ),
                ),
                (
                    "table_capacity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Укажите сколько максимум человек может поместиться за столом",
                        verbose_name="Вместительность стола",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("general hall", "Общий зал"),
                            ("VIP hall", "VIP зал"),
                            ("terrace", "Терраса"),
                        ],
                        default="general hall",
                        help_text="Укажите расположение стола",
                        max_length=50,
                        verbose_name="Расположение стола",
                    ),
                ),
            ],
            options={
                "verbose_name": "Стол",
                "verbose_name_plural": "Столы",
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_reservation",
                    models.DateField(
                        help_text="Выберите число, на которое хотите забронировать столик",
                        verbose_name="Дата бронирования столика",
                    ),
                ),
                (
                    "time_reservation",
                    models.TimeField(
                        help_text="Выберите время, на которое хотите забронировать столик",
                        verbose_name="Время бронирования столика",
                    ),
                ),
                (
                    "count_people",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Введите количество человек",
                        validators=[django.core.validators.MaxValueValidator(20)],
                        verbose_name="Количество человек",
                    ),
                ),
                (
                    "wishes",
                    models.TextField(
                        blank=True,
                        help_text="Напишите Ваши пожелания",
                        null=True,
                        verbose_name="Особые пожелания",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations_customer",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Заказчик брони",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="restaurant.table",
                        verbose_name="Номер стола",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронь",
                "verbose_name_plural": "Брони",
            },
        ),
    ]
