# Generated by Django 5.2.6 on 2025-10-09 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Reservation",
        ),
    ]
