# Generated by Django 5.2.6 on 2025-10-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_delete_reservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="values",
            field=models.TextField(blank=True, null=True, verbose_name="Ценности"),
        ),
    ]
