# Generated by Django 5.2.6 on 2025-10-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_alter_table_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="location",
            field=models.CharField(
                choices=[
                    ("general hall", "Общий зал"),
                    ("VIP hall", "VIP зал"),
                    ("terrace", "Терраса"),
                ],
                default="general hall",
                help_text="Укажите расположение стола",
                max_length=50,
                verbose_name="Расположение стола",
            ),
        ),
    ]
