# Generated by Django 5.2.6 on 2025-10-09 14:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurant", "0002_delete_reservation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_reservation",
                    models.DateField(
                        help_text="Выберите число, на которое хотите забронировать столик",
                        verbose_name="Дата бронирования столика",
                    ),
                ),
                (
                    "time_reservation",
                    models.TimeField(
                        help_text="Выберите время, на которое хотите забронировать столик",
                        verbose_name="Время бронирования столика",
                    ),
                ),
                (
                    "count_people",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Введите количество человек",
                        validators=[django.core.validators.MaxValueValidator(20)],
                        verbose_name="Количество человек",
                    ),
                ),
                (
                    "wishes",
                    models.TextField(
                        blank=True,
                        help_text="Напишите Ваши пожелания",
                        null=True,
                        verbose_name="Особые пожелания",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations_customer",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Заказчик брони",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="restaurant.table",
                        verbose_name="Номер стола",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронь",
                "verbose_name_plural": "Брони",
            },
        ),
    ]
