# Generated by Django 5.2.6 on 2025-10-12 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="long_reservation",
            field=models.PositiveIntegerField(
                default=2,
                help_text="Введите количество часов, на сколько хотите забронировать столик, но не меньше 2x",
                validators=[django.core.validators.MinValueValidator(2)],
                verbose_name="Количество часов брони",
            ),
        ),
    ]
